### ISSUE TITLE
Use icon_url to annotate build status

### ISSUE THREAD

**Issue by nils-werner** [drone-plugins/drone-slack#10]
Slack allows you to set an `icon_url` for each message: <https://api.slack.com/methods/chat.postMessage>

It would be awesome if drone would set it to a green checkmark/red X when the build succeeded or failed.

**Comment by tboerger** [comment]
Doesn't sound too complicated

**Comment by Jean85** [comment]
I don't think you should use an icon... The older behaviour was better, simply setting the "color" option on the payload, like it's explained here: https://api.slack.com/docs/attachments#color

**Comment by tboerger** [comment]
> I don't think you should use an icon... The older behaviour was better, simply setting the "color" option on the payload, like it's explained here: https://api.slack.com/docs/attachments#color

But we are also using icons for slack-blame, so I'm fine with adding config options to override the default behavior.

**Comment by appleboy** [comment]
Hi all,

I create PR #20 to add `PLUGIN_IMAGE_URL` string flag to support this issue.

**Comment by tboerger** [comment]
So #23 implements most of it, otherwise I would suggest the slack-blame plugin which is even more customizable
