### ISSUE TITLE
Helper function datetime does not match documentation

### ISSUE THREAD

**Issue by andreipoe** [drone-plugins/drone-slack#106]
The [documentation page](http://plugins.drone.io/drone-plugins/drone-slack/) lists `datetime` as a helper with a single argument, e.g. `{{datetime build.started}}`, but the function expects 3 arguments:

```
Evaluation error: Helper 'datetime' called with wrong number of arguments, needed 3 but got 1
```

Looking at the source code in [drone/drone-template-lib:template/helpers.go#L62](https://github.com/drone/drone-template-lib/blob/master/template/helpers.go#L62), it looks like `datetime` should be called as, for example, `{{ datetime build.started "15:04" "" }}`. But `build.started` is an integer and `datetime` expects a float, resulting in the following error when called as previously exemplified:

```
Evaluation error: Helper datetime called with argument 0 with type int64 but it should be float64
```

It doesn't currently seem possible to pass a float value to `datetime`, so either a helper should be added to allow create converting integers to floats, or the `datetime` function should allow an integer to be passed in directly.

**Comment by tboerger** [comment]
In the meantime you could do a typecast, soon I will build a breaking change version which will include sane template helpers based on https://github.com/drone/funcmap, as this really kills all custom template strings this will be a new tagged release with a major version change.

**Comment by andreipoe** [comment]
Thanks. That sounds good.

How do you currently do typecasts in templates?

**Comment by waterdrop01** [comment]
Hi @tboerger 

Same issue than @andreipoe

![Screenshot from 2021-07-06 21-30-40](https://user-images.githubusercontent.com/47316824/124656411-74772b80-dea1-11eb-840c-9f5050ba0a47.png)

And here is my `.drone.yml`

```
- name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack-drone-webhook
      channel: alert-drone
      link_names: true
      template: >
        {{#success build.status}}✅{{else}}🐞{{/success}} Build #{{build.number}} of {{repo.name}}@{{build.tag}}

        📝 `{{commit.message}}`
        🙇 {{commit.author}}

        🕐 {{datetime build.started "02.01.2006 15:04" "Europe/Berlin"}}

        🌐 {{build.link}}
```

Any idea how to cast `int64` to `float64` in the template?

Thanks!

Victor

**Comment by ErvalhouS** [comment]
Similar issue to https://github.com/drone-plugins/drone-slack/issues/123#issuecomment-990980525
