### ISSUE TITLE
Documentation doesn't match drone website

### ISSUE THREAD

**Issue by ProLoser** [drone-plugins/drone-slack#29]
It's been really frustrating for me, the documentation linked here doesn't match the drone plugin website: http://readme.drone.io/plugins/slack/ and it seems the one on the website DOES work.

![image](https://cloud.githubusercontent.com/assets/67395/18734055/5c87ef26-8025-11e6-9ca6-faaf0da4fad2.png)

This is what I'm seeing, I wanted to know where some of the components of the template came from (was hoping to see it in the source code) so that I could repurpose by (for example) having a link to the release on github or something.

**Comment by donny-dont** [comment]
The DOCS.md in master is for 0.5. The one at http://readme.drone.io/plugins/slack/ is for the 0.4 release and generated from https://github.com/drone-plugins/drone-slack/blob/release/0.4/DOCS.md.
