### ISSUE TITLE
Git commit message?

### ISSUE THREAD

**Issue by bschuedzig** [drone-plugins/drone-slack#41]
Hello,

is there any possibility to include the commit message in the notification? I was trying to find any examples or remarks on that without success.

Thank you very much for you work on the plugin!

Best,
  Ben

**Comment by alexanderturner** [comment]
This used to be here but seems to have disappeared in drone 0.5. Any ideas guys?

**Comment by alexanderturner** [comment]
https://github.com/drone-plugins/drone-slack/pull/44

**Comment by bschuedzig** [comment]
Found out that you can use the normal environment variables in the template. For me just putting ${DRONE_COMMIT_MESSAGE} in the template works.

**Comment by tboerger** [comment]
Since #44 have been merged you can simply update the template to include the message from the available variables.
