### ISSUE TITLE
Access to the $DRONE_DEPLOY_TO variable

### ISSUE THREAD

**Issue by daniel-ac-martin** [drone-plugins/drone-slack#51]
It would be nice to have access to the $DRONE_DEPLOY_TO variable in order to include the environment being deployed to in notifications.

**Comment by bradrydzewski** [comment]
please send a PR to add the field and we'll merge

**Comment by daniel-ac-martin** [comment]
PR raised. Apologies for the delay.

**Comment by tboerger** [comment]
Solved via #55
