### ISSUE TITLE
Broken build on slack error

### ISSUE THREAD

**Issue by fortis** [drone-plugins/drone-slack#54]
We getting broken build when notification couldn't be sent (slack server unavailable, for example)
I think that drone-slack plugin should return `exit code 0` in that case, and maybe this behavior should be configurable

screenshot to make things clear
![image](https://user-images.githubusercontent.com/1042494/26852614-44783d22-4b28-11e7-9fd5-4829c9a43c44.png)

**Comment by bradrydzewski** [comment]
For consistency purposes, all plugins that I create return a non-zero exit code when the fail to perform their primary task. While I appreciate the comment, this is not something I'm looking to change at this time. I would therefore recommend forking and running a custom version if you would like to override the default behavior.
