### ISSUE TITLE
Notification of build start

### ISSUE THREAD

**Issue by gtaylor** [drone-plugins/drone-slack#6]
Would be nice to have the option to send an optional notification when the build starts. Might not be a sensible default, but it would help us avoid the context switching in checking a browser tab if we are in a hurry.

**Comment by netbe** [comment]
+ 1

**Comment by bradrydzewski** [comment]
closing since this is handled at the Drone level and not at the individual plugin level. This is somewhat enabled in 0.5 at the Drone level but will require use of custom templates

**Comment by dvmorris** [comment]
@bradrydzewski  Could you provide some information on how to implement a "build start" slack notification in drone 0.5? You mentioned that it's handled at the Drone level, but I'm not sure how to do it in this version. Thanks!
