### ISSUE TITLE
Support for secrets for slack webhook url

### ISSUE THREAD

**Issue by vishal24tuniki** [drone-plugins/drone-slack#61]
Is there a plan to add support for using drone secrets for slack webhook url?

**Comment by tboerger** [comment]
It is already supported, just name the secret `slack_webhook` and you should be fine.

**Comment by vishal24tuniki** [comment]
Thanks a lot @tboerger , it would be great if it was mentioned in the doc http://plugins.drone.io/drone-plugins/drone-slack/

**Comment by tboerger** [comment]
> Thanks a lot @tboerger , it would be great if it was mentioned in the doc http://plugins.drone.io/drone-plugins/drone-slack/

The docs will get updated soonish.
