### ISSUE TITLE
Add support for link-names=1 

### ISSUE THREAD

**Issue by vasicvuk** [drone-plugins/drone-slack#67]
It should be nice to have an option to enable **link_names** when sending webhook request.  This will enable tagging people or channels.

https://api.slack.com/incoming-webhooks

It is simple parameter in json that is sent.

**Comment by tboerger** [comment]
Sorry, but can you explain what you are talking about? I don't get what you are requesting.

**Comment by vasicvuk** [comment]
Slack webhooks gives option to mention Simeone In messages with @username. This currently is not working if you put @username In template. This is enabled by adding list_names: 1 In JSON payload.

**Comment by donny-dont** [comment]
@vasicvuk have you looked at slack-blamer? It actually uses the slack api rather than a webhook and is much more fully featured.

**Comment by vasicvuk** [comment]
Yes but i tought that this is deprecated plugin or so because link to the Docs is not working from GitHub repo.

**Comment by tboerger** [comment]
Next time you should mention `link_names` instead of `list_names` and clearly explain what you want to archive, than somebody else will understand it directly and can suggest a solution.

A pull request to add this option is welcome.

**Comment by donny-dont** [comment]
slack-blame isn't deprecated. We use it quite a bit internally. It might not have been updated because we internally are on an ancient version of Drone

**Comment by bradrydzewski** [comment]
@vasicvuk I am going to close this issue. Please send a pull request if you want to see it implemented
