### ISSUE TITLE
document template language

### ISSUE THREAD

**Issue by mmlb** [drone-plugins/drone-slack#68]
The docs page has a couple of sections with info on templates (template reference and template function reference), but they only give info on the extra features this plugin provides over the template engine being used. No where is the template language/engine used documented, which from https://github.com/drone-plugins/drone-slack/blob/master/template.go#L13 I gather to be handle bars.

I'd open a PR adding the one or 2 line blurb but could not find where the files are that get rendered on http://plugins.drone.io/drone-plugins/drone-slack/

**Comment by tboerger** [comment]
This plugin is documented at https://github.com/drone/drone-plugin-index/blob/master/content/drone-plugins/drone-slack/index.md but maybe it makes more sense to add a small guide to the general Drone docs because this templating is used on multiple plugins.

**Comment by mmlb** [comment]
Ah there it is, thanks. Maybe I should move discussion over to drone-plugin-index?

**Comment by bradrydzewski** [comment]
closing based on above comments
