### ISSUE TITLE
Add time-taken to slack-message.

### ISSUE THREAD

**Issue by cheif** [drone-plugins/drone-slack#7]
Hi!
We're currently using travis but is trying out drone, one thing I miss from travis is the time-taken in the slack-message, IMO that would be a sensible default, is this something that others also would like?
In that case I might try to build it myself.

**Comment by bradrydzewski** [comment]
we added templates a while back to customize messages and the timestamps and duration were included. See http://readme.drone.io/usage/notify/#template-data:d1fea7f63b32cc4bab67588d2fde8aa7
