### ISSUE TITLE
datetime  Evaluation error: argument 0 with type int64 but it should be float64

### ISSUE THREAD

**Issue by den-vasyliev** [drone-plugins/drone-slack#72]
Great plugin - thanks a lot!

Minor:
http://plugins.drone.io/drone-plugins/drone-slack/
**_Issue:_**
"datetime
converts a unix timestamp to a date time string. Example **{{datetime build.started}}**"
**_But_** 
1. Should be e.g. *started:* {{datetime 1519654914.0 "Mon Jan _2 15:04:05 2006" "EET"}}
2. "Evaluation error: Helper datetime called with argument 0 with type int64 but it should be float64"
template.go - 90: func toDatetime(timestamp float64, layout, zone string) string
main.go - 185: Started:  c.Int64("build.started"),
plugin.go - 29: Started  int64

Thank you.

**Comment by bradrydzewski** [comment]
you can use the `datetime` function to convert to a human-friendly date. For example `{{datetime build.started}}`

**Comment by den-vasyliev** [comment]
Yes i can but its not worked for me. And why i mentioned before.

**Comment by bradrydzewski** [comment]
if you think it is broken please send a patch

**Comment by den-vasyliev** [comment]
Thank you!

Done:

diff --git a/template.go b/template.go
index 1f9c0ec..fd62990 100644
--- a/template.go
+++ b/template.go
@@ -87,7 +87,7 @@ func toDuration(started, finished float64) string {
        return fmt.Sprintln(time.Duration(finished-started) * time.Second)
 }
 
-func toDatetime(timestamp float64, layout, zone string) string {
+func toDatetime(timestamp int64, layout, zone string) string {
        if len(zone) == 0 {
                return time.Unix(int64(timestamp), 0).Format(layout)
        }

**Tests done with denvasyliev/slack.**

**Fixed issue:** 
![screen shot 2018-02-26 at 18 49 43](https://user-images.githubusercontent.com/2145808/36683285-e04808ea-1b25-11e8-9352-5e7c13be7fa0.png)

**Need to fix documentation** http://plugins.drone.io/drone-plugins/drone-slack/:

- converts a unix timestamp to a date time string. Example {{datetime build.started}}
+converts a unix timestamp to a date time string. Example {{datetime build.started "Mon Jan _2 15:04:05 2006" "EET"}}

Works fine for first look :)

**Comment by waterdrop01** [comment]
I have the exact same issue, described here: https://github.com/drone-plugins/drone-slack/issues/106#issuecomment-875027179

**Comment by ErvalhouS** [comment]
Similar issue to https://github.com/drone-plugins/drone-slack/issues/123#issuecomment-990980525
