### ISSUE TITLE
Support multiple channels

### ISSUE THREAD

**Issue by andrewmclagan** [drone-plugins/drone-slack#74]
Adding support for multiple channels would be helpful. 

For example it would be great to notify: `#deployments, #logging` so devs are able to see heads-up on what deployments are effecting logging - one use case im sure there are many more.

**Comment by donny-dont** [comment]
Why not just have two notify steps?

**Comment by donny-dont** [comment]
@andrewmclagan you can keep your YAML dry with anchors. See https://learnxinyminutes.com/docs/yaml/ for an example on it. This should work fine in Drone I use it in slack blame for multiple different notifications there.

**Comment by bradrydzewski** [comment]
agreed w/ above comments. You can define multiple steps and use anchors to keep it dry, or you can fork the plugin, or when the .drone.js file is available in a future release you can do something like below. So for these reasons, I don't think we need to alter the plugin

 ```
['foo','bar'].forEach(channel => pipeline.start({image: 'plugins/slack', channel }) )
```
