### ISSUE TITLE
Update to raymond 2.0.2

### ISSUE THREAD

**Issue by mvdan** [drone-plugins/drone-slack#76]
I just spent a good twenty minutes trying to figure out why my mustache/handlebars/raymond template wasn't working.

The result, in the end, was that I was trying to use raymond's `#equal` helper: https://github.com/aymerick/raymond#the-equal-helper

But since the vendored copy here is from mid 2015, that feature isn't available. Could we update to a release, like 2.0.2 from just a few days ago?

**Comment by tboerger** [comment]
If we get https://github.com/drone/drone-template-lib/pull/1 merged I will update this plugin to use this lib which already bundles raymond 2.0.2.

**Comment by mvdan** [comment]
Great, thank you.

**Comment by mvdan** [comment]
@tboerger friendly ping - that PR is now merged :) I can submit the PR updating this library if that would make things easier for you.

**Comment by tboerger** [comment]
This version should be already part of this plugin, so I'm closing this issue.

**Comment by mvdan** [comment]
@tboerger so now I assume we simply wait for a new release to be published as a docker image to get the update? Or should I do anything manually to update the drone plugins, like re-pulling their images?

**Comment by tboerger** [comment]
Just add pull: true to your drone file or manually pull the image. It is already part of the releases.
