### ISSUE TITLE
Expand environment variables on templates?

### ISSUE THREAD

**Issue by fsouza** [drone-plugins/drone-slack#82]
Hello hello,
I was playing around with drone deployments and custom parameters and found a use case where it would be useful to be able to use one of the custom parameters in the notification message, but that would require being able to expand environment variables, which is currently not supported.

Would a PR adding that feature be considered?

Thanks!

**Comment by tboerger** [comment]
If reading env variables gets enabled it's a potential security issue as even the slack webhook gets injected as environment variable.

**Comment by fsouza** [comment]
@tboerger yeah I realized that after playing with a wrapper for a little bit. Perhaps if drone could provide a list of parameters that were passed to the deployment, then the plugin could have that in the context when rendering the template.

**Comment by Morriz** [comment]
Can this be reopened? We have multiple drone installations listening to the same repo, and doing CD. We need to report back which instance was successful. This can only be done by parameterizing. Please allow us to use env vars. We are using drone in a controlled environment and no outside meddling with env can happen.

**Comment by tboerger** [comment]
That is just for you the case. I would prefer to integrate the new plugin lib for this plugin, than you would get the system env variables into the template without allowing any env variable as a security issue.
