### ISSUE TITLE
Improvement: commit messages since last successful build

### ISSUE THREAD

**Issue by hkeio** [drone-plugins/drone-slack#86]
It's cool that we can use `{{build.message}}` to include the last commit message in the template but I'd like to see all commit messages since the last successful build but I'm not sure if this is even possible.

**Comment by bradrydzewski** [comment]
A Drone plugin does not have access to this information. This means you would need to create a new Slack plugin to somehow fetch this information to include in your message. There are currently 3 slack plugins that I am aware of (below), although I'm not aware of any that meet your specific use case, but there is always room for more plugins that perform niche tasks.

http://plugins.drone.io/drone-plugins/drone-slack-blame/
http://plugins.drone.io/target/captains-log/
http://plugins.drone.io/drone-plugins/drone-slack/

**Comment by tboerger** [comment]
Since this isn't a feature we would implement here, could we close this pr?

**Comment by bradrydzewski** [comment]
yes, I think we can close this since it is out of scope for this plugin. @hkeio if you have any questions about writing a custom plugin feel free to post to our [discourse forum](https://discourse.drone.io). And if you create a custom plugin, be sure to register with our plugin registry :)
