### ISSUE TITLE
link-names update is missing in Config of main.go

### ISSUE THREAD

**Issue by kinlu** [drone-plugins/drone-slack#93]
As part of https://github.com/drone-plugins/drone-slack/issues/67, the ``link_names`` has been updated to ``link-names`` in d85365109df986575cd5e431f1a9ca9cd86d842a.  But the same update is missing in the config mapping:
```
		Config: Config{
			Webhook:   c.String("webhook"),
			Channel:   c.String("channel"),
			Recipient: c.String("recipient"),
			Username:  c.String("username"),
			Template:  c.String("template"),
			ImageURL:  c.String("image"),
			IconURL:   c.String("icon.url"),
			IconEmoji: c.String("icon.emoji"),
			LinkNames: c.Bool("link_names"),
		},
```
``LinkNames: c.Bool("link_names")`` should've been ``LinkNames: c.Bool("link-names")``

So currently the ``link-names`` parameter is not working.

**Comment by tboerger** [comment]
Good catch, maybe you could also provide a pull request to fix it?
